/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal.assessment;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.StringTokenizer;

/**
 *
 * @author jatinrughwani
 */
public class AdminAppointments extends javax.swing.JPanel {
    String nm[]; //public variable - available in all the things
int count=0;
        String ping = "";


    /**
     * Creates new form AdminAppointments
     */
    public AdminAppointments() {
        initComponents();
         nm = new String[100];
        pname.removeAllItems();
        pname.addItem("-");
        paid.setEditable(false);
        paide.setVisible(false);
        notpaid.setVisible(false);
        
        try
        {
            
 FileReader fr = new FileReader("appointments.txt");//tells which file
            BufferedReader sReader = new BufferedReader(fr);//opens the reader
            String oneStudent = "";
    
            while((oneStudent = sReader.readLine()) !=null)
            {
               
                StringTokenizer st = new StringTokenizer (oneStudent, ","); // "," is used to seperate data in text file. st is variable name
                String a = st.nextToken();     
                String b = st.nextToken();
                String c = st.nextToken();
                String d = st.nextToken();
                String e = st.nextToken();
                String f = st.nextToken();
                String g = st.nextToken();
                String h = st.nextToken();
                String i = st.nextToken();
                String j = st.nextToken();
                
                pname.addItem(b+ " " + c);
                
                }
                sReader.close();
                
        }
    catch(Exception er)
                    {
                        System.out.println("System Not Working");
                    }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pname = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bo = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        paid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        notpaid = new javax.swing.JRadioButton();
        paide = new javax.swing.JRadioButton();

        pname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Patient Name");

        jButton1.setText("Load");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bo.setColumns(20);
        bo.setRows(5);
        jScrollPane1.setViewportView(bo);

        jLabel2.setText("Paid:");

        jButton2.setText("Edit Payment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(notpaid);
        notpaid.setText("Not Paid");

        buttonGroup1.add(paide);
        paide.setText("Paid");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(33, 33, 33)
                        .addComponent(paide)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paid, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notpaid)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notpaid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paide)
                        .addGap(27, 27, 27))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
        {
            
 FileReader fr = new FileReader("appointments.txt");//tells which file
            BufferedReader sReader = new BufferedReader(fr);//opens the reader
            String oneStudent = "";
    
            while((oneStudent = sReader.readLine()) !=null)
            {
               
                StringTokenizer st = new StringTokenizer (oneStudent, ","); // "," is used to seperate data in text file. st is variable name
                String a = st.nextToken();     
                String b = st.nextToken();
                String c = st.nextToken();
                String d = st.nextToken();
                String e = st.nextToken();
                String f = st.nextToken();
                String g = st.nextToken();
                String h = st.nextToken();
                String i = st.nextToken();
                String j = st.nextToken();
                
                if(pname.getSelectedItem().equals(b+ " " + c)){
                    String ans = "Name: " + b + " " +c + "\n" + "Age: " + d + "\n" + "Sex: " + e + "\n" + "Issue: " + f + "\n" + "Date: " + g + "\n" + "Time: " + h + "\n" + "Doctor ID: " + i + "\n" + "Status: " + j;
                        bo.setText(ans);
                        
                        try
        {
            FileReader fre = new FileReader ("paid.txt");
            BufferedReader br = new BufferedReader(fre);
            String oneRec = "";
            
            while ((oneRec = br.readLine()) !=null)
            {
                StringTokenizer ste = new StringTokenizer (oneRec, ","); // "," is used to seperate data in text file. st is variable name
                String ab = ste.nextToken();     
                String bc = ste.nextToken();    
                
                if (ab.equals(a)){
                    paid.setText(bc);
                    ping = ab+"";
                }
                
            }
            fr.close();
        }
        
        catch (Exception er)
        {
            System.out.println("System Not Working 1");
        }
                        
                }
                
                }
                sReader.close();
                
        }
    catch(Exception er)
                    {
                        System.out.println("System Not Working");
                    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
paide.setVisible(true);
        notpaid.setVisible(true);
try
        {
            FileReader fr = new FileReader ("paid.txt");
            BufferedReader br = new BufferedReader(fr);
            String oneRec = "";
            count = 0;
            
            while ((oneRec = br.readLine()) !=null)
            {
                nm[count] = oneRec;
                count = count+1;
            }
        }
        
        catch (Exception er)
        {
            System.out.println("System Not Working 2");
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
paid.setEditable(false);
boolean male1 = true;

String paids = "";


try
{
    String idEdit = ping;
    FileWriter fr = new FileWriter("paid.txt", false);
    PrintWriter pr = new PrintWriter (fr);
    
    
    for (int i = 0; i<count; i++)
    {
        
            System.out.println("hi");

        StringTokenizer tk = new StringTokenizer(nm[i],",");
        String pai = tk.nextToken();
        String  ides = tk.nextToken();
        

        
        if (idEdit.equals(pai))
        {
            //copy new data from the text fields
            if (paide.isSelected())
            {
                 pr.println( ping+ "," + "Yes");
                 male1 = false;
            }
            
            if (notpaid.isSelected())
            {
                 pr.println( ping+ "," + "No");;
                 male1 = false;
            }
            
           
            
            
            }
        
        else
        {
            pr.println(nm[i]);
        }
        
               
    }
    pr.close();
}
catch (Exception er)
        {
            System.out.println("System Not Working 2");
        }

if(male1==false){
    javax.swing.JOptionPane.showMessageDialog(null, "Saved!", "Information",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    
    
}




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton notpaid;
    private javax.swing.JTextField paid;
    private javax.swing.JRadioButton paide;
    private javax.swing.JComboBox<String> pname;
    // End of variables declaration//GEN-END:variables
}
