/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal.assessment;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.StringTokenizer;

/**
 *
 * @author jatinrughwani
 */
public class Booked extends javax.swing.JPanel {

    /**
     * Creates new form Booked
     */
    public Booked() {
        initComponents();
        booked.setEditable(false);
        
            try
                {
                FileReader freee = new FileReader ("appointments.txt");
                BufferedReader breee = new BufferedReader (freee);
                String oneStudent = "";
                
                while((oneStudent = breee.readLine()) !=null){
                StringTokenizer stefe = new StringTokenizer (oneStudent, ",");
                String abcd = stefe.nextToken().trim();
                String bcde = stefe.nextToken().trim();
                String cdef = stefe.nextToken().trim();
                String defg = stefe.nextToken().trim();
                String efgh = stefe.nextToken().trim();
                String fghi = stefe.nextToken().trim();
                String ghij = stefe.nextToken().trim(); 
                String hijk = stefe.nextToken().trim(); 
                String ijkl = stefe.nextToken().trim(); 
                String jklm = stefe.nextToken().trim(); 
                
                try
    {
    FileReader fr = new FileReader ("patientLoggedIn.txt");
    BufferedReader br = new BufferedReader (fr);
    String oneStu = "";
            
    while ((oneStu = br.readLine()) !=null)
    {           
    StringTokenizer st = new StringTokenizer (oneStu, ",");
    String a = st.nextToken().trim();
    String b = st.nextToken().trim();
    String c = st.nextToken().trim();
    String d = st.nextToken().trim();
    String e = st.nextToken().trim();
    String f = st.nextToken().trim();
    String g = st.nextToken().trim();
    int h = Integer.parseInt(st.nextToken());
    
    try
                {
                FileReader free = new FileReader ("doctor.txt");
                BufferedReader bree = new BufferedReader (free);
                String oneStud = "";
                
                while((oneStud = bree.readLine()) !=null){
                StringTokenizer stef = new StringTokenizer (oneStud, ",");
                String abc = stef.nextToken().trim();
                String bcd = stef.nextToken().trim();
                String cde = stef.nextToken().trim();
                String def = stef.nextToken().trim();
                String efg = stef.nextToken().trim();
                String fgh = stef.nextToken().trim();
                String ghi = stef.nextToken().trim(); 
                
                if(a.equals(abcd))
                {
                    if(ijkl.equals(abc)){
                        booked.setText("Doctor: " + bcd + " " + cde + "\n" + "Doctor Details: " + ghi + "; " + efg + "\n" + "Issue: " + fghi + "\n" + "Date: " + ghij + "\n" + "Time: " + hijk + "\n" + "Satus: " + jklm);
                    }
                    
                
                }   
                }

                bree.close();
                }
                catch(Exception erre)
                {
                System.out.println("System Not Workingf");
                }
    
    }
    br.close();
    }
    catch(Exception er)
    {
    System.out.println("System Not Workingm");
    }
                
                
                }

                breee.close();
                }
                catch(Exception errn)
                {
                System.out.println("System Not Workingl");
                }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        booked = new javax.swing.JTextArea();

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("Book");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Booked");

        booked.setColumns(20);
        booked.setRows(5);
        jScrollPane1.setViewportView(booked);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea booked;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
