/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal.assessment;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.StringTokenizer;

/**
 *
 * @author jatinrughwani
 */
public class DoctorAppointments extends javax.swing.JPanel {
    String nm[]; //public variable - available in all the things
int count=0;
    String patientname = "";
    String patientage = "";
    String patientsex = "";
    String patientissue = "";
    String patientdate = "";
    String patienttime = "";

    /**
     * Creates new form DoctorAppointments
     */
    public DoctorAppointments() {
        initComponents();
        bo.setEditable(false);
                        nm = new String[100];

        pname.removeAllItems();
        pname.addItem("-");
        
        try
        {
            
 FileReader fr = new FileReader("appointments.txt");//tells which file
            BufferedReader sReader = new BufferedReader(fr);//opens the reader
            String oneStudent = "";
    
            while((oneStudent = sReader.readLine()) !=null)
            {
               
                StringTokenizer st = new StringTokenizer (oneStudent, ","); // "," is used to seperate data in text file. st is variable name
                String a = st.nextToken();     
                String b = st.nextToken();
                String c = st.nextToken();
                String d = st.nextToken();
                String e = st.nextToken();
                String f = st.nextToken();
                String g = st.nextToken();
                String h = st.nextToken();
                String i = st.nextToken();
                String j = st.nextToken();
 
                
               try
        {
                FileReader fre = new FileReader("doctorLoggedIn.txt");//tells which file
            BufferedReader sReadere = new BufferedReader(fre);//opens the reader
            String oneStudente = "";
    
            while((oneStudente = sReadere.readLine()) !=null)
            {
               
                StringTokenizer ste = new StringTokenizer (oneStudente, ","); // "," is used to seperate data in text file. st is variable name
                String ab = ste.nextToken();     
                String bc = ste.nextToken();
                String cd = ste.nextToken();
                String de = ste.nextToken();
                String ef = ste.nextToken();
                String fg = ste.nextToken();
                String gh = ste.nextToken();
                
                if (ab.equals(i)){
                    
                    if(j.equals("Pending")){
                    pname.addItem(b+ " " + c);
                    patientname = b+ " " + c;
                    patientage = d;
                    patientsex = e;
                    patientissue = f;
                    patientdate = g;
                    patienttime = h;
                    }
                }
                
                
                }
                sReadere.close();
                
        }
    catch(Exception err)
                    {
                        System.out.println("System Not Working");
                    }
                
                
                
        }
                sReader.close();
                
        }
    catch(Exception er)
                    {
                        System.out.println("System Not Working");
                    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        pname = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bo = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        accept = new javax.swing.JRadioButton();
        decline = new javax.swing.JRadioButton();

        jLabel1.setText("Patient Name");

        pname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Load");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bo.setColumns(20);
        bo.setRows(5);
        jScrollPane1.setViewportView(bo);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Appointments");

        jButton2.setText("Done");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(accept);
        accept.setText("Accept");

        buttonGroup1.add(decline);
        decline.setText("Decline");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(accept)
                        .addGap(18, 18, 18)
                        .addComponent(decline)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accept)
                    .addComponent(decline))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if (pname.getSelectedItem().equals("-")){
    javax.swing.JOptionPane.showMessageDialog(null, "Please choose an patient's name", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
}
else{
        String ans = "Name: " + patientname + "\n" + "Age: " + patientage + "\n" + "Sex: " + patientsex + "\n" + "Issue: " + patientissue + "\n" + "Date: " + patientdate + "\n" + "Time: " + patienttime ;
bo.setText(ans);
}
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

     boolean choose = true;
   
     try
        {
            FileReader fr = new FileReader ("appointments.txt");
            BufferedReader br = new BufferedReader(fr);
            String oneRec = "";
            count = 0;
            
            while ((oneRec = br.readLine()) !=null)
            {
                nm[count] = oneRec;
                count = count+1;
            }
        }
        
        catch (Exception er)
        {
            System.out.println("System Not Working 1");
        }
     
        try
{
    FileWriter fre = new FileWriter("appointments.txt", false);
    PrintWriter pre = new PrintWriter (fre);
    
    
    for (int i = 0; i<count; i++)
    {
        
            System.out.println("hi");

        StringTokenizer tk = new StringTokenizer(nm[i],",");
        String id1 = tk.nextToken();
        String fname = tk.nextToken();
        String lname = tk.nextToken();
        String agee = tk.nextToken();
        String sexp = tk.nextToken();
        String iss = tk.nextToken();
        String dte = tk.nextToken();
        String tme = tk.nextToken();
        String docID = tk.nextToken();
        String pend = tk.nextToken();

        
        if (patientname.equals(fname + " " + lname))
        {
            //copy new data from the text fields
            if (accept.isSelected())
            {
               choose = false;
               javax.swing.JOptionPane.showMessageDialog(null, "Appointment Confirmed, please add to your calendar", "Information",
                javax.swing.JOptionPane.INFORMATION_MESSAGE); 
               pre.println(id1 + "," + fname + "," + lname + "," + agee + "," + sexp + "," + iss + "," + dte + "," + tme + "," + docID + "," + "Confirmed");  
            }
            
            if (decline.isSelected())
            {
            choose = false;
            javax.swing.JOptionPane.showMessageDialog(null, "Appointmet Rejected", "Information",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            pre.println(id1 + "," + fname + "," + lname + "," + agee + "," + sexp + "," + iss + "," + dte + "," + tme + "," + docID + "," + "Rejected");
        }
        }
            else
        {
            pre.println(nm[i]);
        }
            
        
        
        
      
               
    }
    pre.close();
}
catch (Exception err)
        {
            System.out.println("System Not Working 2");
        }

if(choose == true){
    javax.swing.JOptionPane.showMessageDialog(null, "Please confirm or decline", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
}

if (choose == false){
pname.setSelectedItem("-");
bo.setText("");
buttonGroup1.clearSelection();
}


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton accept;
    private javax.swing.JTextArea bo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton decline;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> pname;
    // End of variables declaration//GEN-END:variables
}
