/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal.assessment;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.StringTokenizer;

/**
 *
 * @author jatinrughwani
 */
public class PatientFunds extends javax.swing.JPanel {
 String nm[];
 int count=0;
         String patientID = "";

    /**
     * Creates new form PatientFunds
     */
    public PatientFunds() {
        initComponents();
        nm = new String[100];
        fund.setEditable(false);
        
                
                 try
        {
        FileReader fre = new FileReader ("patientLoggedIn.txt");
        BufferedReader bre = new BufferedReader (fre);
        String oneStue = "";
        
        while ((oneStue = bre.readLine()) !=null){
        StringTokenizer ste = new StringTokenizer (oneStue, ",");
        String ab = ste.nextToken().trim();
        String bc = ste.nextToken().trim();
        String cd = ste.nextToken().trim();
        String de = ste.nextToken().trim();
        String ef = ste.nextToken().trim();
        String fg = ste.nextToken().trim();
        String gh = ste.nextToken().trim();
        int h = Integer.parseInt(ste.nextToken());
        
            fund.setText(h+"");
        patientID = ab;
        
        }
        bre.close();
        }
        catch(Exception err)
        {
        System.out.println("System Not Workingm1");
        }
        
                
                
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fund = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Funds");

        jLabel2.setText("Your Funds");

        jLabel3.setText("Add Funds");

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fund, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        boolean choose = false;
        try
        {
            FileReader fr = new FileReader ("patient.txt");
            BufferedReader br = new BufferedReader(fr);
            String oneRec = "";
            count = 0;
            
            while ((oneRec = br.readLine()) !=null)
            {
                nm[count] = oneRec;
                count = count+1;
            }
        }
        
        catch (Exception er)
        {
            System.out.println("System Not Working 1");
        }
     
        try
{
    FileWriter fre = new FileWriter("patient.txt", false);
    PrintWriter pre = new PrintWriter (fre);
    
    
    for (int i = 0; i<count; i++)
    {
        
            System.out.println("hi");

        StringTokenizer tk = new StringTokenizer(nm[i],",");
        String id1 = tk.nextToken();
        String fname = tk.nextToken();
        String lname = tk.nextToken();
        String agee = tk.nextToken();
        String sexp = tk.nextToken();
        String iss = tk.nextToken();
        String dte = tk.nextToken();
        String tme = tk.nextToken();

        if (patientID.equals(id1))
        {
            //copy new data from the text fields
            if (add.getText().equals(""))
            {
               javax.swing.JOptionPane.showMessageDialog(null, "Please add an amount", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);  
            }
            
            else 
            {
            javax.swing.JOptionPane.showMessageDialog(null, "Funds Added. The changes will be made on the next log in.", "Information",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            pre.println(id1 + "," + fname + "," + lname + "," + agee + "," + sexp + "," + iss + "," + dte + "," + add.getText() );
        }
        }
            else
        {
            pre.println(nm[i]);
        }
            
        
        
        
      
               
    }
    pre.close();
}
catch (Exception err)
        {
            System.out.println("System Not Working 2");
        }

add.setText("");


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField fund;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
